import random

fortunes = [
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may break a confidence.",
    "A faithful friend is a strong defense.",
    "A fresh start will put you on your way.",
    "A friend is a present you give yourself.",
    "A gambler not in the red must play for black.",
    "A golden egg of opportunity falls into your lap this month.",
    "A quiet evening with a good book can be as rewarding as a party.",
    "A short pencil is usually better than a long memory.",
    "A small leak will sink a great ship.",
    "A truly rich life contains love and art in abundance.",
    "Accept something you cannot change, and you will be at peace.",
    "Act in haste and repent at leisure.",
    "Advice is like kissing. It doesn't mean much unless you get it from someone you love.",
    "All the troubles you ever had came because of your tongue.",
    "All things are difficult before they are easy.",
    "An unexpected payment is coming your way.",
    "Be careful about reading health books. You may die of a misprint.",
    "Behind every successful man is a surprised woman.",
    "Change is a denial of the past.",
    "Creativity is a drug I cannot live without.",
    "Curiosity kills boredom. Nothing can kill curiosity.",
    "Discontent is the first step in the progress of a man or nation.",
    "Do not mistake temptation of opportunity for a chance.",
    "Do one thing every day that scares you.",
    "Do what comes natural and the results will be natural.",
    "Don't be afraid of the space between your dreams and reality.",
    "Don't let ambitions strangle your humanity.",
    "Don't let strange cats off your back door.",
    "Don't worry about the stock market. Invest in the human soul.",
    "Each day is a gift. Live each moment fully.",
    "Expect a most wonderful day ahead.",
    "Explore new roads and you'll find new destinations.",
    "Fortune favors the brave.",
    "Good news will come to you by mail.",
    "Good things are supposed to come in threes.",
    "Hard work pays off in the future. Laziness pays off immediately.",
    "Happiness will bring you good health.",
    "Help will come from an unexpected source.",
    "How you look depends on where you are coming from.",
    "If you have something to say, say it now.",
    "If you smile when no one else is around, you really mean it.",
    "If you want the rainbow, you gotta put up with the rain.",
    "In dreams and in love, there are no impossibilities.",
    "It could be better, but it's good enough.",
    "It is better to light one candle than to curse the darkness.",
    "It is fortunate that you are here.",
    "It never rains but it pours.",
    "It takes less time to do a thing right than to explain why you did it wrong.",
    "Keep it simple.",
    "Keep your face to the sunshine and you cannot see the shadow.",
    "Let a smile be your umbrella.",
    "Life is a game, play it to win.",
    "Live each day as if it were your last.",
    "Look closely at your next opportunity.",
    "Look for the dream that keeps coming back. It is your destiny.",
    "Look on the bright side.",
    "Many changes of fortune ground the sails of courage.",
    "Never cut what you can untie.",
    "Never give up. You're not a failure if you don't give up.",
    "Never lose an opportunity to see anything that is beautiful.",
    "Never underestimate the power of a kind word or deed.",
    "No one can do everything, but everyone can do something.",
    "Now is the time to try something new.",
    "People are drawn to you.",
    "Practice makes perfect.",
    "Promise yourself to live your life as a revolution and not just a process.",
    "Put your heart, mind, and soul into even your smallest acts.",
    "Quality questions create a quality life.",
    "Realize deeply that the present moment is all you ever have.",
    "Rest and relaxation is a good medicine.",
    "Smile when you're along. Only then will you realize how good it feels.",
    "Someone you know has a new baby. Congratulations!",
    "Sometimes the majority only means that all the fools are on the same side.",
    "Soon life will become very difficult.",
    "Stand tall. Don't look down.",
    "Stop looking for the light at the end of the tunnel. Start being the light.",
    "Success is a journey, not a destination.",
    "The best is yet to be.",
    "The best way to double your money is to fold it over once and put it back in your pocket.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only way to do great work is to love what you do.",
    "The only way to get rid of temptation is to yield to it.",
    "The person who will never stand in your way has arrived.",
    "The strong person understands how weakness determines strength.",
    "There is a prospect of a thrilling time ahead for you.",
    "There is no mistake so great as that of being always right.",
    "There's a good time coming.",
    "Things are not always what they seem.",
    "Today is a good time to bargain.",
    "Today is going to be a really, really great day for you!",
    "Today it will rain cats and dogs.",
    "Today you shed tears, tomorrow you will laugh.",
    "Too much of a good thing.",
    "Traveling will lead to your romantic and physical desires.",
    "Trust in the power of your intuition.",
    "Trust yourself. You know more than you think you do.",
    "Value your life and the lives of others.",
    "Watch your words, they become your actions.",
    "What is behind you is more important than what is in front of you.",
    "What is the use of running when you are on the wrong road?",
    "What others think of you is none of your business.",
    "When one door closes, another opens.",
    "When the student is ready, the teacher will appear.",
    "Whenever possible, keep it simple.",
    "While there is life, there is hope.",
    "Winners never quit, quitters never win.",
    "You always know how to find your road!",
    "You are a lover of words.",
    "You are always welcome in any gathering.",
    "You are going to let your walk do your talking.",
    "You are in for an interesting but temporary period.",
    "You are not wrong, who deem That my knowledge is from above.",
    "You are very comfortable with traditional things.",
    "You attract people by the richness of your mind.",
    "You can keep smiling, it will improve your appearance.",
    "You cannot depend on your eyes when your imagination is out of focus.",
    "You don't have to seek all the answers, just the right ones.",
    "You have a deep appreciation of beauty.",
    "You have a friendly heart and are well admired.",
    "You have an ambitious spirit and a rapid imagination.",
    "You have an unusual equipment for success, use it properly.",
    "You have the capacity to learn from mistakes. You will learn a lot today.",
    "You have the power to write your own fortune.",
    "You love challenge.",
    "You love peace.",
    "You need to focus on the positive aspects.",
    "You never know who will be watching.",
    "You owe it to yourself to live life to the fullest.",
    "You reveal the truth of others but conceal your own.",
    "You should be able to make money this year.",
    "You will be blessed by good health.",
    "You will be happy and healthy all year.",
    "You will be pleasantly surprised by good news.",
    "You will be successful in your legal matter.",
    "You will become great if you stand firm.",
    "You will do better if you go in the opposite direction.",
    "You will find a new love.",
    "You will have a choice of a new job and a new location.",
    "You will have a nice vacation.",
    "You will have good luck and overcome many hardships.",
    "You will inherit some good luck.",
    "You will live a long, happy life.",
    "You will live to see your children's children.",
    "You will make many changes before settling satisfactorily.",
    "You will meet an old friend who remembers you.",
    "You will meet your life partner by the end of the month.",
    "You will soon be surrounded by good friends and laughter.",
    "You will take control of your life this year.",
    "You will travel far and wide, both pleasure and business.",
    "You will travel to many lands.",
    "You will win success in spite of any opposition.",
    "You will witness a special event.",
    "You'll be the most envied person in your circle.",
    "You're bursting with energy and good health.",
    "You're in for a pleasant surprise.",
    "Your ability to find the silly in the serious will bring you joy.",
    "Your dreams are never silly.",
    "Your family is young, gifted and attractive.",
    "Your hard work will pay off.",
    "Your life will be happy and peaceful.",
    "Your love life will be happy and harmonious.",
    "Your loyalty will be repaid many times.",
    "Your mind is your greatest asset.",
    "Your most valuable asset is your intuition.",
    "Your personality is so magnetic.",
    "Your talents will be recognized and rewarded.",
    "Your watch is 10 minutes slow.",
    "You're a trendsetter.",
    "You're going to have a great day!"
]

def get_fortune():
    return random.choice(fortunes)

if __name__ == "__main__":
    print("🍪 Your fortune cookie says:")
    print(get_fortune())
    print("\nEnjoy your day! 🎉")
